---
sidebar: sidebar 
permalink: concept-aiq-digital-advisor.html 
keywords: concepts, active iq digital advisor, ontap 
summary: BlueXP Digital Advisor ermöglicht Ihnen die Optimierung von Betrieb, Sicherheit und Performance Ihrer ONTAP Cluster. 
---
= Cluster mithilfe des digitalen Beraters von BlueXP optimieren
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP Digital Advisor ermöglicht Ihnen die Optimierung von Betrieb, Sicherheit und Performance Ihrer ONTAP Cluster.



== Funktionen

Mithilfe des digitalen Beraters von BlueXP können Sie den Gesamtstatus Ihres Storage-Systems, allgemeine Informationen zum Systemzustand, Inventar, Planung, Upgrades und wertvolle Erkenntnisse auf Watchlistebene anzeigen.

* Analyse und Optimierung des Zustands Ihrer Storage-Systeme
* Sie erhalten Einblick in alle Risiken für Ihre Storage-Systeme und die Maßnahmen zur Risikominderung
* Analysieren Sie die Performance Ihrer Speichergeräte, indem Sie sich das grafische Format der Performance-Daten anzeigen lassen
* Erfahren Sie mehr über Systeme, die mit ihrer Kapazität von mehr als 90 % oder annähernd 90 % ausgelastet sind
* Informationen über Hardware und Software, die innerhalb der nächsten 6 Monate abgelaufen sind oder deren Ablauf nahe steht
* Aktualisieren Sie die ONTAP Firmware Ihres Storage-Systems mithilfe von Ansible




== Unterstützte ONTAP-Systeme

Digital Advisor liefert Informationen zu allen lokalen ONTAP Systemen und Cloud Volumes ONTAP Systemen, die mit Ihrem NSS Konto (NetApp Support Site) verknüpft sind.



== Weitere Informationen

https://["Digitale Berater-Dokumentation"^]
