---
sidebar: sidebar 
permalink: concept-onprem-ontap.html 
keywords: ontap, cluster, discover, manage, discovering, fas, aff, discover onprem, discover aff cluster, discover cluster, add cluster, active iq, digital wallet 
summary: BlueXP kann die ONTAP Cluster erkennen, die auf All Flash FAS/FAS Controllern und ONTAP Select ausgeführt werden. Wenn Sie BlueXP um lokale ONTAP Systeme erweitern, können Sie alle Ihre Storage- und Datenbestände über eine einzige Benutzeroberfläche verwalten. 
---
= Erfahren Sie mehr über das lokale ONTAP Cluster-Management in BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP kann die ONTAP Cluster erkennen, die auf All Flash FAS/FAS Controllern und ONTAP Select ausgeführt werden. Wenn Sie BlueXP um lokale ONTAP Systeme erweitern, können Sie alle Ihre Storage- und Datenbestände über eine einzige Benutzeroberfläche verwalten.



== Funktionen

* Managen Sie NFS- und CIFS-Volumes
* Zugriff auf den ONTAP System Manager für jeden verwalteten Cluster über BlueXP
* Überwachung von Zustand und Performance mit BlueXP-Analyse und Kontrolle
* BlueXP Services ermöglichen Datenreplizierung, Backup, Scan, Klassifizierung und Tiering von Daten
* Statusinformationen zu Hardware- und Softwareverträgen finden Sie im BlueXP Digital Wallet




== Kosten

Ein Preis könnte damit verbunden sein, aber es hängt von folgenden Faktoren ab:

* Unabhängig davon, ob Sie einen Connector bereitstellen, um Ihre Cluster zu erkennen und zu verwalten.
+
Sie können den Connector in der Cloud oder vor Ort installieren. Bei der Installation eines Connectors in der Cloud fallen Kosten an.

* Egal, ob Sie BlueXP Services wie Backup und Recovery, Tiering und Klassifizierung nutzen.

