---
settings:
  name: On-premises ONTAP clusters
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: ONTAP-Cluster-Dokumentation vor Ort
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/whats-new.html"
    - title: Bekannte Einschränkungen
      url: "/reference-limitations.html"
  - title: Los geht's
    entries:
    - title: ONTAP-Cluster-Management vor Ort
      url: "/concept-onprem-ontap.html"
    - title: Erkennen von ONTAP Clustern vor Ort
      url: "/task-discovering-ontap.html"
  - title: Management von lokalen ONTAP-Clustern
    entries:
    - title: Direktes Management von Clustern
      url: "/task-manage-ontap-direct.html"
    - title: Verwalten von Clustern, die über einen Connector erkannt wurden
      url: "/task-manage-ontap-connector.html"
    - title: Cluster-Informationen und Vertragsdetails
      url: "/task-view-cluster-info.html"
    - title: Cluster mithilfe des digitalen Beraters von BlueXP optimieren
      url: "/concept-aiq-digital-advisor.html"
    - title: Entfernen einer lokalen ONTAP-Arbeitsumgebung
      url: "/task-remove-on-prem.html"
  - title: Wissen und Support
    entries:
    - title: Für den Support anmelden
      url: "/task-support-registration.html"
    - title: Holen Sie sich Hilfe
      url: "/task-get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
