---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, system manager, unsupported features 
summary: Bekannte Einschränkungen identifizieren Plattformen, Geräte oder Funktionen, die von dieser Version des Produkts nicht unterstützt werden oder nicht korrekt mit dem Produkt zusammenarbeiten. Lesen Sie diese Einschränkungen sorgfältig durch. 
---
= Bekannte Einschränkungen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bekannte Einschränkungen identifizieren Plattformen, Geräte oder Funktionen, die von dieser Version des Produkts nicht unterstützt werden oder nicht korrekt mit dem Produkt zusammenarbeiten. Lesen Sie diese Einschränkungen sorgfältig durch.



== Nicht unterstützte Cluster

On-Premises-ONTAP-Cluster, die mit SAML-Authentifizierung konfiguriert sind, werden von BlueXP nicht unterstützt.



== Einschränkungen von System Manager

Die folgenden Funktionen von System Manager werden von BlueXP nicht unterstützt:

* Cluster-Einrichtung
+
Nachdem Sie die Management-IP-Adresse festgelegt und das Admin-Passwort in einem On-Prem ONTAP-Cluster konfiguriert haben, können Sie das Cluster in BlueXP erkennen.

* Rollenbasierte Zugriffssteuerung (nur Connector)
+
Die rollenbasierte Zugriffssteuerung über den System-Manager wird nicht unterstützt, wenn ein lokales ONTAP-Cluster mithilfe eines Connectors erkannt und gemanagt wird. Sie werden aufgefordert, während der Bestandsaufnahme Ihre Admin-Anmeldedaten einzugeben. Diese Anmeldedaten werden für alle aus System Manager ergriffenen Aktionen verwendet.

+
Bei der Option Direct Discovery werden Sie aufgefordert, sich bei jedem Öffnen der Arbeitsumgebung mit Ihren ONTAP-Anmeldedaten einzuloggen.

* Cloud-Backup-Aktivierung
+
Cloud Backup kann direkt aus dem Backup und Recovery von BlueXP auf einem lokalen Cluster aktiviert werden. https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-ontap-backup-to-cloud.html["Erste Schritte"^]

* On-Demand-Upgrades
+
Firmware und Software können nicht nach Bedarf aktualisiert werden.

* Globale Suche
* Benutzeroberflächeneinstellungen

