---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, system manager, unsupported features 
summary: Bekannte Einschränkungen identifizieren Plattformen, Geräte oder Funktionen, die von dieser Version des Produkts nicht unterstützt werden oder nicht korrekt mit dem Produkt zusammenarbeiten. Lesen Sie diese Einschränkungen sorgfältig durch. 
---
= Bekannte Einschränkungen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bekannte Einschränkungen identifizieren Plattformen, Geräte oder Funktionen, die von dieser Version des Produkts nicht unterstützt werden oder nicht korrekt mit dem Produkt zusammenarbeiten. Lesen Sie diese Einschränkungen sorgfältig durch.



== Einschränkungen in Bezug auf ASA r2-Systeme

* Sie können NetApp ASA r2-Systeme in BlueXP  erkennen, wenn Sie BlueXP  im Standardmodus oder im eingeschränkten Modus verwenden. Die Erkennung von ASA r2-Systemen wird nicht unterstützt, wenn BlueXP  im privaten Modus verwendet wird.
* Nachdem Sie ein NetApp ASA r2-System erkannt und die Arbeitsumgebung geöffnet haben, werden Sie direkt zu System Manager weitergeleitet.
+
Für ASA r2 Systeme sind keine anderen Managementoptionen verfügbar. Sie können die Standardansicht nicht verwenden und BlueXP Services nicht aktivieren.



https://docs.netapp.com/us-en/asa-r2/index.html["Erfahren Sie mehr über ASA r2-Systeme"^]



== Nicht unterstützte Cluster

On-Premises-ONTAP-Cluster, die mit SAML-Authentifizierung konfiguriert sind, werden von BlueXP nicht unterstützt.



== Einschränkungen von System Manager

Die folgenden Funktionen von System Manager werden von BlueXP nicht unterstützt:

* Cluster-Einrichtung
+
Nachdem Sie die Management-IP-Adresse festgelegt und das Admin-Passwort auf einem lokalen ONTAP-Cluster konfiguriert haben, können Sie das Cluster in BlueXP erkennen.

* Rollenbasierte Zugriffssteuerung (nur Connector)
+
Die rollenbasierte Zugriffssteuerung über den System-Manager wird nicht unterstützt, wenn ein lokales ONTAP-Cluster mithilfe eines Connectors erkannt und gemanagt wird. Sie werden aufgefordert, während der Bestandsaufnahme Ihre Admin-Anmeldedaten einzugeben. Diese Anmeldedaten werden für alle aus System Manager ergriffenen Aktionen verwendet.

+
Bei der Option Direct Discovery werden Sie aufgefordert, sich bei jedem Öffnen der Arbeitsumgebung mit Ihren ONTAP-Anmeldedaten einzuloggen.

* BlueXP Aktivierung für Backup und Recovery (Cloud Backup)
+
Die Cluster-Version muss „9.13.1“ sein, um das Backup und Recovery von BlueXP aus System Manager zu ermöglichen.

+
Wenn Sie einen Cluster mit einem Connector erkannt haben, können Sie den System Manager (erweiterte Ansicht) nicht verwenden, um Backup und Recovery zu ermöglichen. Sie können jedoch Backup und Recovery auf einem lokalen Cluster direkt aus BlueXP aktivieren. https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["Erste Schritte"^]

* On-Demand-Upgrades
+
Bedarfsgesteuerte Upgrades von Firmware und Software sind nicht verfügbar, wenn es sich bei der Cluster-Version um ONTAP 9.9.1 oder eine ältere Version handelt.

+
Wenn Sie über einen Connector verfügen, können Sie keine Updates von Ihrem lokalen Rechner aus vornehmen, nur von einem Server, auf den Sie mit BlueXP zugreifen können.

* Globale Suche
* Benutzeroberflächeneinstellungen

