---
sidebar: sidebar 
permalink: task-discovering-ontap.html 
keywords: ontap, cluster, discover, manage, discovering, fas, aff, discover onprem, discover aff cluster, discover cluster, add cluster, active iq, digital wallet 
summary: Lokale ONTAP-Cluster aus BlueXP entdecken, um Volumes zu managen und erweitertes Management mit ONTAP System Manager, das von BlueXP erhältlich ist, durchzuführen. 
---
= Erkennen von ONTAP Clustern vor Ort
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Lokale ONTAP-Cluster aus BlueXP entdecken, um Volumes zu managen und erweitertes Management mit ONTAP System Manager, der über BlueXP erhältlich ist, durchzuführen.



== Discovery- und Management-Optionen

BlueXP bietet zwei Möglichkeiten zum Erkennen und Managen Ihrer lokalen ONTAP-Cluster:

Erkennung über einen Konnektor:: Mit dieser Option können Sie Cluster mit ONTAP 8.3 und höher verwalten, indem Sie die folgenden Funktionen verwenden:
+
--
* Die Ansicht „Standard“, die grundlegende Volume-Vorgänge bereitstellt
* Die erweiterte Ansicht für Management über System Manager (unterstützt von ONTAP 9.10.0 und höher)
* Integration in BlueXP Services für Datenreplizierung, Backup und Recovery, Datenklassifizierung und Daten-Tiering


Für diese Option ist ein Connector erforderlich, den Sie bei einem Cloud-Provider oder bei Ihnen vor Ort installieren können.

--
Direkte Bestandsaufnahme:: Mit dieser Option können Sie Cluster mit ONTAP 9.12.1 und höher mit System Manager verwalten. Es sind keine anderen Management-Optionen verfügbar. Die Standardansicht kann nicht verwendet werden, und Datenservices können nicht aktiviert werden.
+
--
Für diese Option ist kein Connector erforderlich.

Wenn Sie auf System Manager auf einem lokalen ONTAP-Cluster mit 9.12.1 oder höher mit Verbindung zum BlueXP-Service zugreifen, werden Sie aufgefordert, den Cluster direkt über BlueXP zu verwalten. Wenn Sie dieser Eingabeaufforderung folgen, wird der Cluster in BlueXP mithilfe der Option für die direkte Erkennung erkannt.

--


Sobald die Cluster entdeckt wurden, stehen sie als Arbeitsumgebung auf dem BlueXP Canvas zur Verfügung.

Wenn Sie sich entscheiden, die andere Discovery-Option zu einem späteren Zeitpunkt zu verwenden, müssen Sie den On-Prem-Cluster als separate Arbeitsumgebung auf dem Canvas entdecken. Sie haben dann die Möglichkeit, die andere Arbeitsumgebung zu entfernen.



== Anforderungen

Stellen Sie vor der Erkennung Ihres lokalen ONTAP-Clusters sicher, dass Sie die folgenden Anforderungen erfüllt haben.



=== Allgemeine Anforderungen

* Sie sollten mit BlueXP loslegen, was die Anmeldung und Einrichtung eines Kontos umfasst.
+
https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html["Erfahren Sie, wie Sie BlueXP zum Einsatz bringen"^]

* Sie benötigen die Cluster-Management-IP-Adresse und das Passwort für das Admin-Benutzerkonto.
* BlueXP erkennt ONTAP-Cluster mithilfe von HTTPS. Wenn Sie benutzerdefinierte Firewallrichtlinien verwenden, muss der ONTAP-Cluster eingehenden HTTPS-Zugriff über Port 443 ermöglichen.
+
Die standardmäßige "mgmt"-Firewall-Richtlinie ermöglicht eingehenden HTTPS-Zugriff von allen IP-Adressen. Wenn Sie diese Standardrichtlinie geändert haben oder wenn Sie eine eigene Firewall-Richtlinie erstellt haben, müssen Sie das HTTPS-Protokoll mit dieser Richtlinie verknüpfen und den Zugriff über den Connector-Host aktivieren.





=== Anforderungen für die Erkennung und Verwaltung von Konnektors

* Das On-Premises-Cluster muss ONTAP 8.3 oder höher ausführen.
* Ein Connector muss bei einem Cloud-Provider oder vor Ort installiert sein.
+
Wenn kalte Daten in die Cloud verschoben werden sollen, sollten Sie die Anforderungen für den Connector prüfen, je nachdem, wo Sie kalte Daten Tiering möchten.

+
** https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html["Erfahren Sie mehr über Steckverbinder"^]
** https://docs.netapp.com/us-en/bluexp-setup-admin/task-managing-connectors.html["Wechseln zwischen den Anschlüssen"^]
** https://docs.netapp.com/us-en/bluexp-tiering/concept-cloud-tiering.html["Weitere Informationen zu BlueXP Tiering"^]


* Der Connector-Host muss ausgehenden HTTPS-Zugriff über Port 443 ermöglichen.
+
Wenn sich der Connector in der Cloud befindet, ist die gesamte ausgehende Kommunikation durch die vordefinierte Sicherheitsgruppe zulässig.





=== Anforderungen an direkte Erfassung und Management

* Das On-Premises-Cluster muss ONTAP 9.12.1 oder höher ausführen.
* Der Cluster muss über ein- und ausgehende Verbindungen zum BlueXP-Service verfügen:
+
\https://cloudmanager.cloud.netapp.com/ontap-service/check-service-connection

* Der Computer, den Sie für den Zugriff auf die BlueXP-Konsole verwenden, muss über eine Netzwerkverbindung mit dem lokalen ONTAP-Cluster verfügen, ähnlich wie Sie Verbindungen zu anderen Ressourcen in Ihrem privaten Netzwerk bereitstellen würden.




== Cluster erkennen

Entdecken Sie Ihre lokalen ONTAP-Cluster auf der Leinwand in BlueXP. Wenn Sie die Erkennung starten, erkennt BlueXP den Cluster wie folgt:

* Wenn Sie über einen aktiven Connector verfügen, der über eine Verbindung zu Ihrem ONTAP-Cluster verfügt, verwendet BlueXP diesen Connector, um das Cluster zu erkennen und zu managen.
* Wenn Sie keinen Connector haben oder Ihr Connector keine Verbindung zum ONTAP-Cluster hat, verwendet BlueXP automatisch die Option für direkte Erkennung und Management.


.Schritte
. Wählen Sie im Navigationsmenü die Option *Storage > Canvas* aus.
. Klicken Sie auf der Seite Arbeitsfläche auf *Arbeitsumgebung hinzufügen* und wählen Sie *On-Premises*.
. Wählen Sie neben dem On-Premises-ONTAP *Discover*.
. Geben Sie auf der Seite _Discover_ die Cluster-Management-IP-Adresse und das Passwort für das Admin-Benutzerkonto ein.
. Wenn Sie den Cluster direkt erkennen (ohne Connector), können Sie *Save the credentials* auswählen.
+
Wenn Sie diese Option auswählen, müssen Sie die Anmeldeinformationen nicht jedes Mal erneut eingeben, wenn Sie die Arbeitsumgebung öffnen. Diese Anmeldedaten sind nur mit Ihrem BlueXP Benutzer verknüpft. Sie werden nicht von anderen Personen in Ihrem Konto gespeichert.

. Wählen Sie * Entdecken*.
+
Wenn Sie keinen Connector haben und die IP-Adresse nicht über BlueXP erreichbar ist, werden Sie aufgefordert, einen Connector zu erstellen.



.Ergebnis
BlueXP entdeckt den Cluster und fügt ihn als Arbeitsumgebung auf dem Canvas hinzu. Sie können jetzt mit dem Verwalten des Clusters beginnen.

* link:task-manage-ontap-direct.html["Informieren Sie sich, wie Sie Cluster, die direkt erkannt werden, managen"]
* link:task-manage-ontap-connector.html["Erfahren Sie, wie Sie mit einem Connector erkannte Cluster verwalten"]

